### ISSUE TITLE
ERROR conda.core.link:_execute(730)

### ISSUE THREAD

**Issue by xuanxuan-Jin** [aryarm/varCA#47]
**Describe the bug**
ERROR conda.core.link:_execute(730): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.1-r351_0'.

**To Reproduce**
Could not create conda environment from /lustre/grp/bitcap/jinxx/source/varCA/rules/../envs/prepare.yml:
**Expected behavior**

here is my log file :
Building DAG of jobs...
Creating conda environment envs/prepare.yml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /lustre/grp/bitcap/jinxx/source/varCA/rules/../envs/prepare.yml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.1-r351_0'.
Rolling back transaction: ...working... done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.1-r351_0
location of failed script: /lustre/grp/bitcap/jinxx/source/varCA/.snakemake/conda/942e2afa/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: /lustre/grp/bitcap/jinxx/source/varCA/.snakemake/conda/942e2afa/share/bioconductor-genomeinfodbdata-1.2.1-0/GenomeInfoDbData_1.2.1.tar.gz: FAILED
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 2fd536521151e2ff37217b5cfee8cec4:
https://bioconductor.org/packages/3.9/data/annotation/src/contrib/GenomeInfoDbData_1.2.1.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.1.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.1_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   415  100   415    0     0    374      0  0:00:01  0:00:01 --:--:--   374
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (7) Failed to connect to bioarchive.galaxyproject.org port 443: No route to host
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (7) Failed to connect to depot.galaxyproject.org port 443: No route to host

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 142, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 59, in install
    unlink_link_transaction.execute()
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 281, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 744, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.1-r351_0
location of failed script: /lustre/grp/bitcap/jinxx/source/varCA/.snakemake/conda/942e2afa/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: /lustre/grp/bitcap/jinxx/source/varCA/.snakemake/conda/942e2afa/share/bioconductor-genomeinfodbdata-1.2.1-0/GenomeInfoDbData_1.2.1.tar.gz: FAILED
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 2fd536521151e2ff37217b5cfee8cec4:
https://bioconductor.org/packages/3.9/data/annotation/src/contrib/GenomeInfoDbData_1.2.1.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.1.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.1_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   415  100   415    0     0    374      0  0:00:01  0:00:01 --:--:--   374
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (7) Failed to connect to bioarchive.galaxyproject.org port 443: No route to host
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (7) Failed to connect to depot.galaxyproject.org port 443: No route to host

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/grp/bitcap/jinxx/miniconda3/bin/conda-env", line 7, in <module>
    sys.exit(main())
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1374, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1085, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1116, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1132, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1136, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1059, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/gateways/logging.py", line 61, in filter
    record.msg = record.msg % new_args
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 132, in __repr__
    errs.append(e.__repr__())
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 71, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/lustre/grp/bitcap/jinxx/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 90, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 852

  File "/lustre/grp/bitcap/jinxx/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 333, in create

**Comment by Jaureguy760** [comment]
This issue is now resolved!

The error was caused by the `bioconductor-genomeinfodbdata` package in `prepare.yml`—the old version was no longer available or its post-link script failed. The solution was to update `prepare.yml` to use the latest available version of this package (or remove the version specifier entirely), then recreate the environment using mamba.

After making this change and recreating the environment, the example data run now completes successfully. If you encounter this error, please update your `prepare.yml` as described above, remove any cached environments, and recreate with mamba:

```bash
rm -rf .snakemake/conda
mamba env create -f envs/prepare.yaml
```

Thank you for reporting this!
